name: MLOps Training Pipeline

on:
  push:
    branches: [ main ]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Authenticate DVC with Google Drive
        run: |
          # Create the credentials file from the GitHub secret
          echo '${{ secrets.GDRIVE_CREDENTIALS_DATA }}' > client_secrets.json

      - name: Pull Data with DVC
        run: |
          dvc pull -v

      - name: Run the ZenML Pipeline
        run: |
          python run.py